[project]
name = "mvt-encoder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jupyterlab>=4.3.6",
    "protobuf>=6.30.2",
    "ruff>=0.11.2",
]

[tool.ruff]
extend-include = ["*.ipynb"]
